### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by treshugart** [mrjoelkemp/node-source-walk#12]
References https://github.com/mrjoelkemp/node-detective-es6/issues/3.

First step is probably to experiment with using a version of [acorn](https://github.com/marijnh/acorn) that supports JSX. Possibly [acorn-jsx](https://github.com/RReverser/acorn-jsx).

**Comment by mrjoelkemp** [comment]
Using acorn-jsx is a great idea. You should be able to swap acorn for that, set the `plugins` field as a default option, and add a quick test to make sure the parser doesn't throw on jsx code.

You can then npm link your local node-source-walk within detective-es6 and test that the detective works on your jsx code.

I'm always nervous touching the parser and doing minor releases. I'd gladly merge the PR and then test on the other detectives (like detective-amd and detective-cjs) to make sure they don't break with the minor bump.

Any help is appreciated. Super excited to get jsx support.

**Comment by mrjoelkemp** [comment]
Fixed via https://github.com/mrjoelkemp/node-source-walk/pull/13
